### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by gotsalyuk** [cweijan/vscode-ssh#1]
При нажатии на кнопку добавить подключение, кидает алерт

**Comment by cweijan** [comment]
Can you provide a screenshot？

**Comment by gotsalyuk** [comment]
![image](https://user-images.githubusercontent.com/43486979/80664073-f7437000-8abf-11ea-995b-044d65ca174e.png)

**Comment by cweijan** [comment]
Thanks feedback, 1.0.3 fix this bug.
