### ISSUE TITLE
Cannot Delete Connection

### ISSUE THREAD

**Issue by Adrianm6254** [cweijan/vscode-ssh#10]
I am having an issue with deleting a connection.
I select the connection I wish to delete by clicking on the trash can.
I tried selecting "YES" and typing in "YES' 
But the connection still remains.  

I am on version 1.6.0

**Comment by asgradeng** [comment]
Same issue here.

**Comment by cweijan** [comment]
Thanks feedback. 1.6.1 has been fix.
