### ISSUE TITLE
Handshake failed: no matching client->server cipher

### ISSUE THREAD

**Issue by Jimwi** [cweijan/vscode-ssh#15]
ssh client version: 1.7.1
vscode version: 1.48.2
Windows version:  windows 10 Enterprise LTSC

Ssh client cannot connect to remote server. Vscode reports "Handshake failed: no matching client->server cipher" error.

**Comment by Jimwi** [comment]
Maybe many problems can lead to this error. You probably solved some of them.
I updated ssh client's version to 1.7.6, but this error still remains

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/103601594-eeefde80-4f44-11eb-94ce-40cbcc9400c9.png)
Since 1.7.7, Support special connect cipher.

**Comment by Jimwi** [comment]
可以用了，谢谢。niubility
