### ISSUE TITLE
Change terminal picture

### ISSUE THREAD

**Issue by alst74** [cweijan/vscode-ssh#16]
Would be nice to update the connection icon:
https://www.google.com/imgres?imgurl=http%3A%2F%2Fcdn.onlinewebfonts.com%2Fsvg%2Fimg_255394.png&imgrefurl=https%3A%2F%2Fwww.onlinewebfonts.com%2Ficon%2F255394&tbnid=rJsnKSCfY5zJsM&vet=12ahUKEwiQv5qxi9LtAhWVzyoKHcY1DH0QMygAegUIARCRAQ..i&docid=GKPtj5i_Fcp5WM&w=980&h=980&q=terminal%20type%3Asvg&safe=off&ved=2ahUKEwiQv5qxi9LtAhWVzyoKHcY1DH0QMygAegUIARCRAQ
![img_255394](https://user-images.githubusercontent.com/7159370/102324605-576d2080-3f82-11eb-8780-53b39f62641f.png)

**Comment by cweijan** [comment]
update light theme icon to this, will release on next version.
![image](https://user-images.githubusercontent.com/27798227/102572606-8670c700-4127-11eb-9e91-28b3a44f62af.png)

**Comment by cweijan** [comment]
Update on 1.7.5.
