### ISSUE TITLE
Hide or remove username from connection bar

### ISSUE THREAD

**Issue by alst74** [cweijan/vscode-ssh#17]
Would be nice to NOT display username@host from connection bar. Atleast if there's a config to change this. If you have many servers, especially when they are called prod/test/ etc you'll get a lot's of them and bar might look cluttered.

**Comment by cweijan** [comment]
What do you think is a better way to display?

**Comment by cweijan** [comment]
I using IP, so it work fine.

**Comment by alst74** [comment]
I'd prefer just an alias (name) in the bar. It's because I need name to describe the servers. Eg:
Jenkins Prod
Jenkins Test
Confluence Prod

Note, this is MY preffered choice, therefore it would be nice if it was configurable (on global level). Maybe similar to how you can configure your Linux prompt:
<name>@<username><hostname>
and if I like shorter:
<name>
👍

**Comment by cweijan** [comment]
I think this is indeed a good way, version 1.7.4 has been use connection name as default title.
