### ISSUE TITLE
Can not follow symbolic links

### ISSUE THREAD

**Issue by sin-sato** [cweijan/vscode-ssh#18]
Hi,
Unable to expand tree of symbolic links from 1.7.5.
Is this by design?

**Comment by cweijan** [comment]
Hi, update to 1.7.6

**Comment by sin-sato** [comment]
![cannot-follow-symdir](https://user-images.githubusercontent.com/76929539/103513680-6a528100-4eae-11eb-8a16-3150c64626b9.png)
Even 1.7.6 is useless.

**Comment by cweijan** [comment]
oh, I read it wrong a while ago, now it is indeed prohibited to expand the link, because I cannot determine whether it is a file or a folder

**Comment by sin-sato** [comment]
Okay, I understand.
Thank you for your support.
