### ISSUE TITLE
forward mysql fail

### ISSUE THREAD

**Issue by hoysoft** [cweijan/vscode-ssh#7]
**vscode-ssh 1.5.6**

**forward  redis success**
localHost  127.0.0.1
localPort   6380
remoteHost   127.0.0.1
remotePort   6379

**forward  mysql fail**
localHost  127.0.0.1
localPort   3307
remoteHost   127.0.0.1
remotePort   3306

**Comment by cweijan** [comment]
I can successfully forward MySQL myself. Repair it according to the error information

**Comment by hoysoft** [comment]
![图片](https://user-images.githubusercontent.com/1274558/89985375-8b22fb80-dcad-11ea-8311-3fd5a0b85041.png)

this "Create" button is loop animation

**Comment by hoysoft** [comment]
![图片](https://user-images.githubusercontent.com/1274558/89985569-d806d200-dcad-11ea-98dc-494c5f4f28db.png)

xshell forwarding  is normal

**Comment by cweijan** [comment]
I guess your port 3307 has been listen, open developer tool can get error message.
![image](https://user-images.githubusercontent.com/27798227/89987270-595f6400-dcb0-11ea-8c07-06a3dd3cbd52.png)

**Comment by hoysoft** [comment]
[Embedded Page] [object Object]
workbench.desktop.main.js:sourcemap:1670   ERR listen EACCES: permission denied 127.0.0.1:3307: Error: listen EACCES: permission denied 127.0.0.1:3307
	at Server.setupListenHandle [as _listen2] (net.js:1211:19)
	at listenInCluster (net.js:1276:12)
	at doListen (net.js:1415:7)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)


Changed  port：3308  ， thank  cweijan
