### ISSUE TITLE
Connection name

### ISSUE THREAD

**Issue by zichnt01** [cweijan/vscode-ssh#9]
Hey there, great extension. Could you add the feature to name a connection?

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/90788156-16e4f980-e338-11ea-853e-6bf431b67b57.png)
Have this feature.

**Comment by cweijan** [comment]
Sorry, I'm wrong about the warehouse. It's a good idea, I will implement it to next version.

**Comment by zichnt01** [comment]
Works fine! Thanks for your fast response. 👍
